### ISSUE TITLE
Error when @Aranir tries to create game

### ISSUE THREAD

**Issue by romac** [reminisceme/game-creator#13]
We're running into errors on the dev server when @Aranir tries to create a game:

```
[… a few dozens of the same "Failed board creation" errors …]

[ERROR] [05/24/2015 18:27:36.213] [server-akka.actor.default-dispatcher-107] [akka://server/user/server-service/$Ec/$a] Failed board creation: Not enough data : Page not found.
[ERROR] [05/24/2015 18:27:36.213] [server-akka.actor.default-dispatcher-107] [akka://server/user/server-service/$Ec] Failed board creation: Not enough data : Page not found.
[ERROR] [05/24/2015 18:27:36.228] [server-akka.actor.default-dispatcher-104] [akka.dispatch.Dispatcher] null
java.lang.NullPointerException
        at me.reminisce.service.gameboardgen.questiongen.QuestionGenerator.dispatcher(QuestionGenerator.scala:28)
        at me.reminisce.service.gameboardgen.questiongen.WhoLikedYourPost$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(WhoLikedYourPost.scala:39)
        at me.reminisce.service.gameboardgen.questiongen.WhoLikedYourPost$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(WhoLikedYourPost.scala:34)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

We can't tell if that is because of a real lack of data or because there's an issue with the game-creator itself. In any case, we thought we'd let you know about that `NullPointerException` :)

**Comment by Rabyss** [comment]
This is not because of the lack of data, this exception arises when the game creator picks a certain post from the "postQuestions" table that is not in the "fbPosts" table. This happened often when changing the crawling/database schema. You should first try to drop the database and re-fetch everything. Tell me if this solves the problem.

**Comment by Aranir** [comment]
Romac told me yesterday when we tested that he cleaned the DB before we tried.
So I think that won't solve the problem.

**Comment by Rabyss** [comment]
It seems to be working now, feel free to reopen later.
