### ISSUE TITLE
"key not found: PostReactionNumber" when creating bot game

### ISSUE THREAD

**Issue by romac** [reminisceme/game-creator#85]
I get the following exception after the bot accepts a join request. Then the game fails to be created with the following message: "Unfortunately the game could not be created due to the lack of activity on facebook from one of players".

I'm using a fresh MongoDB database, and I am on game creator version `13021f3e9df1cb6e6e95a6c21edd07788c6533cd`.

```
java.util.NoSuchElementException: key not found: PostReactionNumber
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3$$anonfun$apply$3.apply(FullRandomBoardGenerator.scala:70)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3$$anonfun$apply$3.apply(FullRandomBoardGenerator.scala:69)
	at scala.Option.flatMap(Option.scala:171)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3.apply(FullRandomBoardGenerator.scala:69)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3.apply(FullRandomBoardGenerator.scala:66)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1.apply(FullRandomBoardGenerator.scala:65)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1.apply(FullRandomBoardGenerator.scala:60)
	at me.reminisce.gameboard.board.BoardGenerator$$anonfun$findSomeRandom$3.apply(BoardGenerator.scala:328)
	at me.reminisce.gameboard.board.BoardGenerator$$anonfun$findSomeRandom$3.apply(BoardGenerator.scala:327)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.util.NoSuchElementException: key not found: PostReactionNumber
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3$$anonfun$apply$3.apply(FullRandomBoardGenerator.scala:70)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3$$anonfun$apply$3.apply(FullRandomBoardGenerator.scala:69)
	at scala.Option.flatMap(Option.scala:171)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3.apply(FullRandomBoardGenerator.scala:69)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1$$anonfun$3.apply(FullRandomBoardGenerator.scala:66)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1.apply(FullRandomBoardGenerator.scala:65)
	at me.reminisce.gameboard.board.FullRandomBoardGenerator$$anonfun$me$reminisce$gameboard$board$FullRandomBoardGenerator$$generateBoard$1.apply(FullRandomBoardGenerator.scala:60)
	at me.reminisce.gameboard.board.BoardGenerator$$anonfun$findSomeRandom$3.apply(BoardGenerator.scala:328)
	at me.reminisce.gameboard.board.BoardGenerator$$anonfun$findSomeRandom$3.apply(BoardGenerator.scala:327)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Rabyss** [comment]
Fix incoming in #86
